apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-go-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: learning-go
  template:
    metadata:
      labels:
        app: learning-go
    spec:
      containers:
      - name: nginx
        image: nginx:1.10 
        #image: gerraywang/learning-go # 変更箇所 DOCKERHUB_REPO_NAME
